# The URL the site will be built for
base_url = "https://wilsonjholmes.github.io/mensch/"

# The site title and description; used in feeds by default.
title = "mensch"
description = "Zola theme designed for humans."
generate_feed = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "gruvbox-dark", filename = "syntax-theme-dark.css" },
  { theme = "gruvbox-light", filename = "syntax-theme-light.css" },
]

[extra]
# Put all your custom variables here
mensch_color_theme = "gruvbox"
mensch_links = [
    { title = "YouTube", url = "https://youtube.com", icon = "youtube" },
    { title = "Twitter", url = "https://twitter.com", icon = "twitter" },
    { title = "GitHub", url = "https://github.com", icon = "github" },
    { title = "GitLab", url = "https://gitlab.com", icon = "gitlab" },
    { title = "Linkedin", url = "https://www.linkedin.com", icon = "linkedin" },
    { title = "E-Mail", url = "mailto:johndoe@email.com", icon = "mail" },
    { title = "RSS", url = "atom.xml", icon = "rss" },
    { title = "GPG", url = "https://gnupg.org/", icon = "key" }
]
mensch_site_source = "https://github.com/wilsonjholmes/mensch"

mensch_show_reading_time = true

mensch_date_format = "%B %e, %Y"

