name = "mensch"
description = "Zola theme designed for humans."
license = "UNLICENSE"
homepage ="https://github.com/wilsonjholmes/mensch"
# The minimum version of Zola required
min_version = "0.15.2"
# An optional live demo URL
demo = "https://wilsonjholmes.github.io/mensch/"


[markdown]
render_emoji = true

highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "gruvbox-dark", filename = "syntax-theme-dark.css" },
  { theme = "gruvbox-light", filename = "syntax-theme-light.css" },
]

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
mensch_color_theme = "" # gruvbox or solarized
mensch_links = [
]
mensch_site_source = ""

mensch_show_word_count = true
mensch_show_reading_time = true

mensch_date_format = "%a %b %e, %Y"



# The theme author info: you!
[author]
name = "Wilson J Holmes"
homepage = "https://wilsonjholmes.xyz"


