name = "mensch"
description = "A blog theme for humans"
license = "Unlicense"
homepage = "https://github.com/wilsonjholmes/mensch"
min_version = "0.15.2"
demo = "example.com"

[extra]
mensch_sticky = true
mensch_reverse = false
mensch_theme = ""
mensch_links = [
]

[author]
name = "Vincent Prouillet"
homepage = "https://www.vincentprouillet.com"

[original]
author =  "Wilson J. Holmes"
homepage = "http://wilsonjholmes.xyz"
repo = "https://www.github.com/wilsonjholmes/mensch"
